# Generated by Django 5.0.4 on 2024-04-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО кандидата')),
                ('sberposition', models.CharField(max_length=250, verbose_name='Позиция в структуре Сбера')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
