# Generated by Django 5.0.4 on 2024-04-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userresume',
            options={'verbose_name': 'Резюме кандидата', 'verbose_name_plural': 'Резюме кандидатов'},
        ),
    ]
