# Generated by Django 5.0.4 on 2024-04-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_userresume_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResume2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.PositiveIntegerField(verbose_name='Пол')),
                ('fio', models.CharField(max_length=250, verbose_name='ФИО')),
                ('work_exprience', models.PositiveIntegerField(verbose_name='Стаж на последнем месте работы')),
                ('responsibilities', models.TextField(verbose_name='Обязанности на последнем месте работы')),
                ('prof_area', models.CharField(max_length=250, verbose_name='Проф. Область на последнем месте работы')),
                ('position', models.CharField(max_length=250, verbose_name='Должность на последнем месте работы')),
                ('achievements', models.TextField(verbose_name='Достижения на последнем месте работы')),
                ('total_work_exprience', models.PositiveIntegerField(verbose_name='Стаж на последнем месте работы')),
                ('prof_tags', models.CharField(max_length=250, verbose_name='Проф теги')),
                ('skills', models.CharField(max_length=250, verbose_name='Навыки')),
                ('hobbies', models.CharField(max_length=250, verbose_name='Интересы')),
                ('key_achievements', models.TextField(verbose_name='Ключевые достижения')),
                ('career_status', models.PositiveIntegerField(verbose_name='Карьерный статус')),
                ('managment_experience', models.PositiveIntegerField(verbose_name='Опыт управления')),
                ('score', models.CharField(max_length=2, verbose_name='Оценка 5+')),
                ('language_skills', models.CharField(max_length=250, verbose_name='Владение языками')),
                ('degree', models.TextField(verbose_name='Образование')),
                ('psychotype', models.CharField(max_length=250, verbose_name='Психологический тип')),
                ('motivations', models.CharField(max_length=250, verbose_name='Мотивация')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Резюме кандидата',
                'verbose_name_plural': 'Резюме кандидатов',
            },
        ),
    ]
