# Generated by Django 5.0.4 on 2024-04-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_userresume2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userresume2',
            options={'verbose_name': 'Резюме кандидата (версия 2)', 'verbose_name_plural': 'Резюме кандидатов (версия 2)'},
        ),
    ]
