# Generated by Django 5.0.4 on 2024-04-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_alter_userresume2_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume2',
            name='total_work_exprience',
            field=models.PositiveIntegerField(verbose_name='Общий стаж'),
        ),
    ]
